services:
  jupyter:
    image: ruk2712/dsci-310-group-17:${IMAGE_TAG:-latest}
    ports:
      - '8888:8888'
    environment:
      - RENV_PATHS_LIBRARY=/renv-library
      - RENV_CONFIG_CACHE_ENABLED=FALSE
    volumes:
      - .:/project:cached
