services:
  rstudio:
    image: ruk2712/dsci-310-group-17:latest
    ports:
      - "8787:8787"
    environment:
      - DISABLE_AUTH=true
      - RENV_CONFIG_AUTOLOAD_ENABLED=FALSE
    volumes:
      - .:/home/rstudio/project
