% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Predicting Billboard \#1 Hits},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Predicting Billboard \#1 Hits}
\author{}
\date{\vspace{-2.5em}Authors: May Eindra Tet Toe, Anastasia Tountas, Tran Anh Thu
Phung, Harry Nguyen}

\begin{document}
\maketitle

\subsection{Summary}\label{summary}

The objective of this analysis is to use publicly available song
information from the Billboard Hot 100 song rankings to investigate the
question:

\textbf{Given various metrics about a song (energy, beats per minute,
etc.), how many weeks, if any, will a song remain at the top position in
the Billboard Hot 100 rankings? Which features contribute most to our
model's predictions?}

\subsection{Introduction}\label{introduction}

The magazine ``Billboard'' is a leading source of information on trends
in music popularity and innovation. Following the launch of the magazine
in 1958, weekly rankings of the top 100 songs in the US have been made
publicly available. (Billboard Staff 2011) The dataset that we have
selected is open-source Tidy Tuesday (Data Science Learning Community
2025) dataset which documents these billboard rankings from August 4th
1958, until January 11th 2025. It provides features such as lyrics,
song-structure, and featured\_artists for each song in the ranking.
These features can then be used for song popularity predictions or music
trend forecasting. In this analysis, we use linear regression to predict
the number of weeks a song remains at the \#1 spot in the rankings, and
assess our model's performance using RMSE, MAE and \(R^2\). Even though
our results show that our regressor has a weak performance, information
regarding feature importances in model decision-making remain useful in
determining a song's overall popularity.

\subsection{Methods and Results}\label{methods-and-results}

\subsubsection{Overview of our
Methodology}\label{overview-of-our-methodology}

The Billboard Hot 100 dataset provides us with two datasets:
\texttt{billboard.csv}, which contains one row per song that reached \#1
along with it's features, and \texttt{topics.csv}, a reference list of
lyrical theme labels (\texttt{lyrical\_topics}). Our team decided to
combine the two datasets to \texttt{billboard\_clean} in order to create
more comprehensive data to better equip our model. Here is an overview
of our data analysis methodology:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Reading \& Wrangling:} read and wrangle the dataset into one
  tidy combined dataset
\item
  \textbf{Exploratory Data Analysis:} explore the data to understand the
  distribution of features and their relationships with the target
  variable
\item
  \textbf{Feature Transformations \& Selection:} applied
  \texttt{log1p()} to skewed variables, one-hot encoded
  \texttt{cdr\_genre}, and collapsed \texttt{simplified\_key} into three
  categories. Then, manually dropped irrelevant columns and used
  \texttt{nearZeroVar()} to remove predictors with near-zero variance.
\item
  \textbf{Model Building \& Evaluation:} split the data 70/30, fit an
  ordinary least squares model using a \texttt{tidymodels} workflow.
  Then, evaluate the model using a repeated 5-fold cross-validation and
  test set metrics (RMSE, \(R^2\), MAE).
\item
  \textbf{Results and Conclusion:} summarize our findings, discuss the
  implications of our results, and suggest potential future work or
  improvements to our analysis
\end{enumerate}

\subsubsection{Load libraries and set
seed}\label{load-libraries-and-set-seed}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(tidytuesdayR)}
\FunctionTok{library}\NormalTok{(knitr)}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(caret)}
\FunctionTok{library}\NormalTok{(tidymodels)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsubsection{Reading \& Wrangling our dataset from the web into
R}\label{reading-wrangling-our-dataset-from-the-web-into-r}

\begin{itemize}
\tightlist
\item
  The two datasets were joined using a \texttt{left\_join()} on
  \texttt{lyrical\_topic} (billboard) and
  \texttt{lyrical\_topics}(topics).
\item
  \textbf{Identifier columns} (\texttt{song}, \texttt{artist},
  \texttt{date}) were removed as they are not predictive features.
\item
  \textbf{\texttt{non\_consecutive}} was removed to prevent data leakage
  --- it can only be determined after a song has completed its full
  chart run.
\item
  \textbf{\texttt{rating\_1}, \texttt{rating\_2}, \texttt{rating\_3}}
  were removed in favour of \texttt{overall\_rating} (their mean) to
  avoid multicollinearity.
\item
  \textbf{Free-text columns} were removed avoid the high dimensionality
  and noise associated with Natural Language Processing:
  \texttt{lyrics}, \texttt{u\_s\_artwork}, \texttt{sound\_effects},
  \texttt{song\_structure}, \texttt{featured\_artists},
  \texttt{songwriters},
  \texttt{songwriters\_w\_o\_interpolation\_sample\_credits},
  \texttt{producers}, \texttt{double\_a\_side}, and
  \texttt{talent\_contestant}.
\item
  \textbf{High-cardinality columns} removed because they generalise
  poorly: \texttt{label}, \texttt{parent\_label}, and
  \texttt{artist\_place\_of\_origin}.
\item
  \textbf{Redundant columns} were removed: \texttt{keys} is replaced by
  \texttt{simplified\_key}; \texttt{cdr\_style} and
  \texttt{discogs\_style} are replaced by \texttt{cdr\_genre} and
  \texttt{discogs\_genre} respectively.
\item
  \textbf{\texttt{discogs\_genre}} was removed in favour of
  \texttt{cdr\_genre} because cdr has more reliable class definitions,
  thus improving internal validity.
\item
  \textbf{Ambiguous columns} were removed:
  \texttt{featured\_in\_a\_then\_contemporary\_play},
  \texttt{featured\_in\_a\_then\_contemporary\_film}, and
  \texttt{featured\_in\_a\_then\_contemporary\_t\_v\_show}.
\item
  All remaining character columns were converted to factors using
  \texttt{as.factor()}, and rows with any missing values were dropped
  with \texttt{drop\_na()}.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load the dataset}
\NormalTok{tuesdata }\OtherTok{\textless{}{-}}\NormalTok{ tidytuesdayR}\SpecialCharTok{::}\FunctionTok{tt\_load}\NormalTok{(}\DecValTok{2025}\NormalTok{, }\AttributeTok{week =} \DecValTok{34}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## ---- Compiling #TidyTuesday Information for 2025-08-26 ----
## --- There are 2 files available ---
## 
## 
## -- Downloading files -----------------------------------------------------------
## 
##   1 of 2: "billboard.csv"
##   2 of 2: "topics.csv"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Extract the datasets}
\NormalTok{billboard }\OtherTok{\textless{}{-}}\NormalTok{ tuesdata}\SpecialCharTok{$}\NormalTok{billboard}
\NormalTok{topics }\OtherTok{\textless{}{-}}\NormalTok{ tuesdata}\SpecialCharTok{$}\NormalTok{topics}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Join the two datasets}
\NormalTok{billboard\_joined }\OtherTok{\textless{}{-}}\NormalTok{ billboard }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{left\_join}\NormalTok{(topics, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"lyrical\_topic"} \OtherTok{=} \StringTok{"lyrical\_topics"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Save raw datasets to data/raw/}
\FunctionTok{dir.create}\NormalTok{(}\StringTok{"../data/raw"}\NormalTok{, }\AttributeTok{recursive =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{showWarnings =} \ConstantTok{FALSE}\NormalTok{)}
\FunctionTok{write\_csv}\NormalTok{(billboard, }\StringTok{"../data/raw/billboard.csv"}\NormalTok{)}
\FunctionTok{write\_csv}\NormalTok{(topics, }\StringTok{"../data/raw/topics.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{billboard\_clean }\OtherTok{\textless{}{-}}\NormalTok{ billboard\_joined }\SpecialCharTok{|\textgreater{}}
  \CommentTok{\# Remove identifier columns}
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{c}\NormalTok{(song, artist, date)) }\SpecialCharTok{|\textgreater{}}
  \CommentTok{\# Remove data{-}leakage column}
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{non\_consecutive) }\SpecialCharTok{|\textgreater{}}
  \CommentTok{\# Remove individual judge scores to avoid multicollinearity}
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{c}\NormalTok{(rating\_1, rating\_2, rating\_3)) }\SpecialCharTok{|\textgreater{}}
  \CommentTok{\# Remove free{-}text columns}
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{c}\NormalTok{(}
\NormalTok{    lyrics,}
\NormalTok{    u\_s\_artwork,}
\NormalTok{    sound\_effects,}
\NormalTok{    song\_structure,}
\NormalTok{    featured\_artists,}
\NormalTok{    songwriters,}
\NormalTok{    songwriters\_w\_o\_interpolation\_sample\_credits,}
\NormalTok{    producers,}
\NormalTok{    double\_a\_side,}
\NormalTok{    talent\_contestant}
\NormalTok{  )) }\SpecialCharTok{|\textgreater{}}
  \CommentTok{\# Remove high{-}cardinality columns}
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{c}\NormalTok{(label, parent\_label, artist\_place\_of\_origin)) }\SpecialCharTok{|\textgreater{}}
  \CommentTok{\# Remove redundant columns and discogs\_genre}
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{c}\NormalTok{(cdr\_style, discogs\_style, keys, discogs\_genre)) }\SpecialCharTok{|\textgreater{}}
  \CommentTok{\# Remove ambiguous columns}
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{c}\NormalTok{(}
\NormalTok{    featured\_in\_a\_then\_contemporary\_play,}
\NormalTok{    featured\_in\_a\_then\_contemporary\_film,}
\NormalTok{    featured\_in\_a\_then\_contemporary\_t\_v\_show}
\NormalTok{  )) }\SpecialCharTok{|\textgreater{}}
  \CommentTok{\# Convert remaining character columns to factors}
  \FunctionTok{mutate}\NormalTok{(}\FunctionTok{across}\NormalTok{(}\FunctionTok{where}\NormalTok{(is.character), as.factor)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{drop\_na}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\subsubsection{Exploratory Data
Analysis}\label{exploratory-data-analysis}

First, we find the summary statistics for our target variable,
\texttt{weeks\_at\_number\_one}, and our key numeric predictors:
\texttt{overall\_rating}, \texttt{bpm}, \texttt{energy},
\texttt{danceability}, \texttt{happiness}, \texttt{acousticness},
\texttt{loudness\_d\_b}, \texttt{front\_person\_age}, and
\texttt{length\_sec}.

\begin{longtable}[]{@{}lrrrrr@{}}
\caption{Summary statistics}\tabularnewline
\toprule\noalign{}
Variable & Mean & SD & Min & Median & Max \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Variable & Mean & SD & Min & Median & Max \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
acousticness & 31.51 & 27.66 & 0 & 23.00 & 98 \\
bpm & 115.50 & 23.69 & 16 & 115.00 & 176 \\
danceability & 62.45 & 15.21 & 14 & 64.00 & 98 \\
energy & 59.81 & 19.62 & 3 & 60.50 & 98 \\
front\_person\_age & 27.97 & 6.51 & 11 & 27.50 & 62 \\
happiness & 62.60 & 24.96 & 4 & 68.00 & 99 \\
length\_sec & 222.88 & 50.12 & 96 & 224.00 & 515 \\
loudness\_d\_b & -9.02 & 3.40 & -23 & -9.00 & -1 \\
overall\_rating & 6.18 & 1.86 & 1 & 6.33 & 10 \\
weeks\_at\_number\_one & 2.91 & 2.49 & 1 & 2.00 & 16 \\
\end{longtable}

Then, we examine the distribution of our target variable,
\texttt{weeks\_at\_number\_one}, to check for skewness.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={Distribution of weeks at number one.}]{billboard_number_one_prediction_files/figure-latex/eda-target-dist-1.pdf}}
\caption{Distribution of weeks at number one.}
\end{figure}

The distribution is heavily right-skewed. The majority of songs spent
only 1 to 3 weeks at \#1, with counts dropping off sharply afterwards. A
small number of songs stayed for 10 or more weeks, forming a long right
tail.

Next, we examine the distributions of the five Spotify audio features,
to identify any skewness that may require transformation before
modelling.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={Distributions of the five Spotify audio features.}]{billboard_number_one_prediction_files/figure-latex/eda-numeric-distributions-1.pdf}}
\caption{Distributions of the five Spotify audio features.}
\end{figure}

\texttt{acousticness} is heavily right-skewed, with most songs clustered
near zero. \texttt{happiness} shows a bimodal pattern with peaks around
30 and around 80. \texttt{energy} is very slightly left-skewed, while
\texttt{bpm} and \texttt{danceability} are roughly normal.

Finally, we compare average \texttt{weeks\_at\_number\_one} by genre to
see whether certain genres are associated with longer chart runs.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={Average weeks at number one by genre.}]{billboard_number_one_prediction_files/figure-latex/eda-genre-1.pdf}}
\caption{Average weeks at number one by genre.}
\end{figure}

Electronic/Dance;Latin seems to have the highest average
(\textasciitilde10 weeks). Pop;Reggae and Folk/Country;March also rank
highly. Mainstream genres like Pop and Rock sit in the middle of the
range. At the lower end, we can find niche genres like
Electronic/Dance;Funk/Soul, averaging to 1 week.

\subsubsection{Feature Transformations}\label{feature-transformations}

Based on the Exploratory Data Analysis, two variables require
transformation before modelling:

\begin{itemize}
\tightlist
\item
  \textbf{\texttt{weeks\_at\_number\_one}} is heavily right-skewed
\item
  \textbf{\texttt{acousticness}} is also heavily right-skewed
\end{itemize}

Therefore, we apply log transformation to these three variables to
compresses the tail and produce a more symmetric target distribution. We
will be using \texttt{log1p()} instead of \texttt{log()} to handle any
zero values in the data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{billboard\_log\_transformed }\OtherTok{\textless{}{-}}\NormalTok{ billboard\_clean }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{log\_weeks\_at\_number\_one =} \FunctionTok{log1p}\NormalTok{(weeks\_at\_number\_one),}
    \AttributeTok{log\_acousticness =} \FunctionTok{log1p}\NormalTok{(acousticness)}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

Moreover, several songs in the dataset were associated with more than
one musical genre (for example, \texttt{Electronic/Dance;\ Latin} or
\texttt{Pop;Funk/Soul}). Treating these combined labels as single
categorical values would incorrectly imply that each combination
represents a distinct genre and would lead to sparse, poorly
interpretable factor levels. To address this, the \texttt{cdr\_gerne}
variable was processed as a multi-label feature. Individual genre were
first separated into their component parts and then encoded as binary
indicator variables using one-hot encoding.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{billboard\_genres }\OtherTok{\textless{}{-}}\NormalTok{ billboard\_log\_transformed }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{separate\_rows}\NormalTok{(cdr\_genre, }\AttributeTok{sep =} \StringTok{";"}\NormalTok{) }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{mutate}\NormalTok{ (}\AttributeTok{cdr\_genre =} \FunctionTok{str\_trim}\NormalTok{(cdr\_genre))}

\NormalTok{billboard\_genres\_wide }\OtherTok{\textless{}{-}}\NormalTok{ billboard\_genres }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{value =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{pivot\_wider}\NormalTok{(}
    \AttributeTok{names\_from =}\NormalTok{ cdr\_genre, }
    \AttributeTok{values\_from =}\NormalTok{ value,}
    \AttributeTok{values\_fill =} \DecValTok{0}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

The \texttt{simplified\_key} variable originally contained 25 levels
representing individual musical keys in standard notation
(e.g.~\texttt{C}, \texttt{Am}, \texttt{Bbm}). Retaining all 25 levels
would generate an excessive number of dummy variable during modelling,
introducing sparsity and increasing the risk of overfitting. To address
this, the keys were collapsed into three musically meaningful
categories: Major (e.g.~\texttt{C}, \texttt{Ab}, \texttt{F}), Minor
(e.g.~\texttt{Am},\texttt{Bbm}, \texttt{Em}), and Multiple Keys.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{billboard\_simplify\_key }\OtherTok{\textless{}{-}}\NormalTok{ billboard\_genres\_wide }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{simplified\_key =} \FunctionTok{case\_when}\NormalTok{(}
\NormalTok{      simplified\_key }\SpecialCharTok{==} \StringTok{"Multiple Keys"}          \SpecialCharTok{\textasciitilde{}} \StringTok{"Multiple Keys"}\NormalTok{,}
      \FunctionTok{str\_ends}\NormalTok{(simplified\_key, }\StringTok{"m"}\NormalTok{)              }\SpecialCharTok{\textasciitilde{}} \StringTok{"Minor"}\NormalTok{,  }
      \ConstantTok{TRUE}                                        \SpecialCharTok{\textasciitilde{}} \StringTok{"Major"}  
\NormalTok{    ) }\SpecialCharTok{|\textgreater{}} \FunctionTok{as.factor}\NormalTok{()}
\NormalTok{  )}

\NormalTok{billboard\_model\_final }\OtherTok{\textless{}{-}}\NormalTok{ billboard\_simplify\_key }\SpecialCharTok{|\textgreater{}} 
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{weeks\_at\_number\_one, }\SpecialCharTok{{-}}\NormalTok{acousticness)}
\end{Highlighting}
\end{Shaded}

\subsubsection{Feature Selection}\label{feature-selection}

\paragraph{Drop Redundant Columns}\label{drop-redundant-columns}

Columns were dropped on conceptual grounds across five categories:

\begin{itemize}
\tightlist
\item
  Demographic identity columns encoding the race and gender of artists,
  songwriters, and producers.
\item
  Artist structure indicators, songwriter/producer role overlap columns.
\item
  Timing-derived columns.
\item
  Lyric redundant content.
\item
  External content.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{columns\_to\_drop }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \CommentTok{\# Demographic identity}
  \StringTok{"artist\_male"}\NormalTok{,}\StringTok{"artist\_white"}\NormalTok{, }\StringTok{"artist\_black"}\NormalTok{, }\StringTok{"songwriter\_male"}\NormalTok{, }\StringTok{"songwriter\_white"}\NormalTok{, }\StringTok{"producer\_male"}\NormalTok{, }\StringTok{"producer\_white"}\NormalTok{, }
  \CommentTok{\# Artist structure}
  \StringTok{"artist\_structure"}\NormalTok{, }\StringTok{"group\_named\_after\_non\_lead\_singer"}\NormalTok{,}
  \CommentTok{\# Songwriter/producer overlaps}
  \StringTok{"artist\_is\_only\_songwriter"}\NormalTok{, }\StringTok{"artist\_is\_only\_producer"}\NormalTok{, }\StringTok{"songwriter\_is\_a\_producer"}\NormalTok{,}
  \CommentTok{\# Timing}
  \StringTok{"instrumental\_length\_sec"}\NormalTok{,  }\StringTok{"intro\_length\_sec"}\NormalTok{,}
  \CommentTok{\# Lyrical content }
  \StringTok{"lyrical\_topic"}\NormalTok{,}\StringTok{"lyrical\_narrative"}\NormalTok{,}
  \CommentTok{\# External content}
  \StringTok{"written\_for\_a\_play"}\NormalTok{, }\StringTok{"written\_for\_a\_film"}\NormalTok{, }\StringTok{"written\_for\_a\_t\_v\_show"}\NormalTok{, }\StringTok{"eurovision\_entry"}\NormalTok{, }\StringTok{"topped\_the\_charts\_by\_multiple\_artist"}\NormalTok{, }\StringTok{"associated\_with\_dance"}\NormalTok{)}

\NormalTok{billboard\_manual\_dropped }\OtherTok{\textless{}{-}}\NormalTok{ billboard\_model\_final }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{all\_of}\NormalTok{(columns\_to\_drop))}
\end{Highlighting}
\end{Shaded}

\paragraph{Drop columns with nearly zero
variance}\label{drop-columns-with-nearly-zero-variance}

Near-zero variance predictors were identified and removed using
\texttt{nearZeroVar()} from the \texttt{caret} package. A predictor was
flagged for removal if it met either of two criteria: its most common
value appeared at least 19 times more frequently than the second most
common value (\texttt{freqCut\ =\ 95/5}), or fewer than 5\% of its
values were unique (\texttt{uniqueCut\ =\ 5}).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Identify and remove near{-}zero variance predictors}
\NormalTok{nzv\_cols }\OtherTok{\textless{}{-}} \FunctionTok{nearZeroVar}\NormalTok{(billboard\_manual\_dropped, }
                        \AttributeTok{freqCut =} \DecValTok{95}\SpecialCharTok{/}\DecValTok{5}\NormalTok{,  }
                        \AttributeTok{uniqueCut =} \DecValTok{5}\NormalTok{,}
                        \AttributeTok{names =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{billboard\_model\_selected }\OtherTok{\textless{}{-}}\NormalTok{ billboard\_manual\_dropped }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{all\_of}\NormalTok{(nzv\_cols))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Save processed dataset}
\FunctionTok{dir.create}\NormalTok{(}\StringTok{"../data/processed"}\NormalTok{, }\AttributeTok{recursive =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{showWarnings =} \ConstantTok{FALSE}\NormalTok{)}
\FunctionTok{write\_csv}\NormalTok{(billboard\_model\_selected, }\StringTok{"../data/processed/billboard\_model\_selected.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsubsection{Regression Model}\label{regression-model}

Split the dataset into training and testing sets, with 705 of the
observations allocated to the training set and 30\% to the testing set.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Train/test split}
\NormalTok{billboard\_split }\OtherTok{\textless{}{-}} \FunctionTok{initial\_split}\NormalTok{(billboard\_model\_selected, }\AttributeTok{prop =} \FloatTok{0.7}\NormalTok{)}
\NormalTok{train\_data }\OtherTok{\textless{}{-}} \FunctionTok{training}\NormalTok{(billboard\_split)}
\FunctionTok{write\_csv}\NormalTok{(train\_data, }\StringTok{"../data/processed/billboard\_model\_training.csv"}\NormalTok{)}
\NormalTok{test\_data }\OtherTok{\textless{}{-}} \FunctionTok{testing}\NormalTok{(billboard\_split)}
\FunctionTok{write\_csv}\NormalTok{(test\_data, }\StringTok{"../data/processed/billboard\_model\_testing.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

A linear regression workflow was constructed using a preprocessing
recipe that dummy-encoded categorical variables, removed near-zero
variance and collinear predictors, and standardized numeric predictors.
The model was fit using ordinary least squares on the training data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm\_recipe }\OtherTok{\textless{}{-}} \FunctionTok{recipe}\NormalTok{(log\_weeks\_at\_number\_one }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ train\_data) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{step\_dummy}\NormalTok{(}\FunctionTok{all\_nominal\_predictors}\NormalTok{(), }\AttributeTok{one\_hot =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{step\_nzv}\NormalTok{(}\FunctionTok{all\_predictors}\NormalTok{()) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{step\_normalize}\NormalTok{(}\FunctionTok{all\_numeric\_predictors}\NormalTok{()) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{step\_lincomb}\NormalTok{(}\FunctionTok{all\_numeric\_predictors}\NormalTok{())}

\NormalTok{lm\_spec }\OtherTok{\textless{}{-}} \FunctionTok{linear\_reg}\NormalTok{() }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{set\_engine}\NormalTok{(}\StringTok{"lm"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{set\_mode}\NormalTok{(}\StringTok{"regression"}\NormalTok{)}

\NormalTok{lm\_workflow }\OtherTok{\textless{}{-}} \FunctionTok{workflow}\NormalTok{() }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{add\_recipe}\NormalTok{(lm\_recipe) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{add\_model}\NormalTok{(lm\_spec)}
\end{Highlighting}
\end{Shaded}

The linear regression workflow was evaluated using repeated 5-fold
cross-validation, stratified by \texttt{log\_weeks\_at\_number\_one} ,
with RMSE, \(R^2\) , and MAE used as performance metrics.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{cv\_folds }\OtherTok{\textless{}{-}} \FunctionTok{vfold\_cv}\NormalTok{(}
\NormalTok{  train\_data,}
  \AttributeTok{v       =} \DecValTok{5}\NormalTok{,}
  \AttributeTok{repeats =} \DecValTok{3}\NormalTok{,}
  \AttributeTok{strata  =}\NormalTok{ log\_weeks\_at\_number\_one}
\NormalTok{)}

\NormalTok{cv\_results }\OtherTok{\textless{}{-}} \FunctionTok{fit\_resamples}\NormalTok{(}
\NormalTok{  lm\_workflow,}
  \AttributeTok{resamples =}\NormalTok{ cv\_folds,}
  \AttributeTok{metrics   =} \FunctionTok{metric\_set}\NormalTok{(rmse, rsq, mae),}
  \AttributeTok{control   =} \FunctionTok{control\_resamples}\NormalTok{(}\AttributeTok{save\_pred =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{)}

\CommentTok{\# Cross{-}validation summary}
\NormalTok{cv\_metrics }\OtherTok{\textless{}{-}} \FunctionTok{collect\_metrics}\NormalTok{(cv\_results)}
\FunctionTok{print}\NormalTok{(cv\_metrics)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 6
##   .metric .estimator   mean     n std_err .config        
##   <chr>   <chr>       <dbl> <int>   <dbl> <chr>          
## 1 mae     standard   0.415     15 0.00599 pre0_mod0_post0
## 2 rmse    standard   0.505     15 0.00674 pre0_mod0_post0
## 3 rsq     standard   0.0626    15 0.0113  pre0_mod0_post0
\end{verbatim}

Fit the model to the training data

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{final\_fit }\OtherTok{\textless{}{-}} \FunctionTok{fit}\NormalTok{(lm\_workflow, }\AttributeTok{data =}\NormalTok{ train\_data)}
\end{Highlighting}
\end{Shaded}

The fitted model was evaluated on the test set by comparing predicted
and observed values using RMSE, \(R^2\) , and MAE.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{test\_predictions }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(final\_fit, }\AttributeTok{new\_data =}\NormalTok{ test\_data) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{bind\_cols}\NormalTok{(test\_data }\SpecialCharTok{|\textgreater{}} \FunctionTok{select}\NormalTok{(log\_weeks\_at\_number\_one)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{rename}\NormalTok{(}
    \AttributeTok{predicted =}\NormalTok{ .pred,}
    \AttributeTok{actual    =}\NormalTok{ log\_weeks\_at\_number\_one}
\NormalTok{  )}

\NormalTok{test\_metrics }\OtherTok{\textless{}{-}}\NormalTok{ test\_predictions }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{metrics}\NormalTok{(}\AttributeTok{truth =}\NormalTok{ actual, }\AttributeTok{estimate =}\NormalTok{ predicted)}

\FunctionTok{print}\NormalTok{(test\_metrics)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 3
##   .metric .estimator .estimate
##   <chr>   <chr>          <dbl>
## 1 rmse    standard      0.502 
## 2 rsq     standard      0.0518
## 3 mae     standard      0.395
\end{verbatim}

\subsubsection{Results}\label{results}

\paragraph{Visualization}\label{visualization}

Actual version predicted weeks at number one on the test set, shown on
the original scale, with the red dashed line indicating perfect
prediction.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rsq\_label }\OtherTok{\textless{}{-}} \FunctionTok{paste0}\NormalTok{(}
  \StringTok{"R\_squared = "}\NormalTok{,}
  \FunctionTok{round}\NormalTok{(}
\NormalTok{    test\_predictions }\SpecialCharTok{|\textgreater{}}
      \FunctionTok{metrics}\NormalTok{(}\AttributeTok{truth =}\NormalTok{ actual, }\AttributeTok{estimate =}\NormalTok{ predicted) }\SpecialCharTok{|\textgreater{}}
      \FunctionTok{filter}\NormalTok{(.metric }\SpecialCharTok{==} \StringTok{"rsq"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
      \FunctionTok{pull}\NormalTok{(.estimate),}
    \DecValTok{3}
\NormalTok{  )}
\NormalTok{)}

\NormalTok{p\_actual\_vs\_predicted }\OtherTok{\textless{}{-}}\NormalTok{ test\_predictions }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{actual\_weeks    =} \FunctionTok{expm1}\NormalTok{(actual),}
    \AttributeTok{predicted\_weeks =} \FunctionTok{expm1}\NormalTok{(predicted)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ actual\_weeks, }\AttributeTok{y =}\NormalTok{ predicted\_weeks)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.4}\NormalTok{, }\AttributeTok{colour =} \StringTok{"steelblue"}\NormalTok{, }\AttributeTok{size =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}
    \AttributeTok{slope     =} \DecValTok{1}\NormalTok{,}
    \AttributeTok{intercept =} \DecValTok{0}\NormalTok{,}
    \AttributeTok{linetype  =} \StringTok{"dashed"}\NormalTok{,}
    \AttributeTok{colour    =} \StringTok{"firebrick"}\NormalTok{,}
    \AttributeTok{linewidth =} \FloatTok{0.8}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{annotate}\NormalTok{(}
    \StringTok{"text"}\NormalTok{,}
    \AttributeTok{x      =} \DecValTok{12}\NormalTok{,}
    \AttributeTok{y      =} \DecValTok{2}\NormalTok{,}
    \AttributeTok{label  =}\NormalTok{ rsq\_label, }
    \AttributeTok{colour =} \StringTok{"firebrick"}\NormalTok{,}
    \AttributeTok{size   =} \DecValTok{4}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title    =} \StringTok{"Actual vs Predicted Weeks at \#1 (Test Set)"}\NormalTok{,}
    \AttributeTok{x        =} \StringTok{"Actual Weeks at \#1"}\NormalTok{,}
    \AttributeTok{y        =} \StringTok{"Predicted Weeks at \#1"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}

\NormalTok{p\_actual\_vs\_predicted}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={Actual vs predicted weeks at number one on the test set (original scale).}]{billboard_number_one_prediction_files/figure-latex/visualization-1-1.pdf}}
\caption{Actual vs predicted weeks at number one on the test set
(original scale).}
\end{figure}

Top 15 predictors by standardized coefficient magnitude, with color
indicating positive or negative effect on the response.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Extract coefficients safely using broom::tidy explicitly}
\NormalTok{coef\_data }\OtherTok{\textless{}{-}}\NormalTok{ broom}\SpecialCharTok{::}\FunctionTok{tidy}\NormalTok{(}\FunctionTok{extract\_fit\_engine}\NormalTok{(final\_fit)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(term }\SpecialCharTok{!=} \StringTok{"(Intercept)"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(}\FunctionTok{abs}\NormalTok{(estimate))) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{slice\_head}\NormalTok{(}\AttributeTok{n =} \DecValTok{15}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{direction =} \FunctionTok{if\_else}\NormalTok{(estimate }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, }\StringTok{"Positive"}\NormalTok{, }\StringTok{"Negative"}\NormalTok{),}
    \AttributeTok{term      =} \FunctionTok{str\_replace\_all}\NormalTok{(term, }\StringTok{"\_"}\NormalTok{, }\StringTok{" "}\NormalTok{) }\SpecialCharTok{|\textgreater{}} \FunctionTok{str\_to\_title}\NormalTok{()}
\NormalTok{  )}

\NormalTok{p\_coefficients }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(}
\NormalTok{  coef\_data,}
  \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(term, }\FunctionTok{abs}\NormalTok{(estimate)), }\AttributeTok{y =}\NormalTok{ estimate, }\AttributeTok{fill =}\NormalTok{ direction)}
\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{(}\AttributeTok{show.legend =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{coord\_flip}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}
    \AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"Positive"} \OtherTok{=} \StringTok{"steelblue"}\NormalTok{, }\StringTok{"Negative"} \OtherTok{=} \StringTok{"firebrick"}\NormalTok{),}
    \AttributeTok{name   =} \StringTok{"Effect on}\SpecialCharTok{\textbackslash{}n}\StringTok{log(weeks + 1)"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title    =} \StringTok{"Top 15 Predictors by Coefficient Magnitude"}\NormalTok{,}
    \AttributeTok{x        =} \ConstantTok{NULL}\NormalTok{,}
    \AttributeTok{y        =} \StringTok{"Standardised Coefficient"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"right"}\NormalTok{)}

\NormalTok{p\_coefficients}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={Top 15 predictors by standardised coefficient magnitude.}]{billboard_number_one_prediction_files/figure-latex/visualization-2-1.pdf}}
\caption{Top 15 predictors by standardised coefficient magnitude.}
\end{figure}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{coef\_data}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 15 x 6
##    term                    estimate std.error statistic  p.value direction
##    <chr>                      <dbl>     <dbl>     <dbl>    <dbl> <chr>    
##  1 Energy                   -0.119     0.0344    -3.45  0.000590 Negative 
##  2 Loudness D B              0.0960    0.0287     3.35  0.000857 Positive 
##  3 Sample                    0.0634    0.0377     1.68  0.0929   Positive 
##  4 Overall Rating            0.0613    0.0203     3.02  0.00260  Positive 
##  5 Vocal Introduction        0.0576    0.0208     2.77  0.00573  Positive 
##  6 Horns Winds              -0.0535    0.0221    -2.42  0.0158   Negative 
##  7 Handclaps Snaps           0.0456    0.0194     2.35  0.0191   Positive 
##  8 Guitar Based             -0.0376    0.0231    -1.63  0.104    Negative 
##  9 Interpolation             0.0350    0.0432     0.810 0.418    Positive 
## 10 Artist Is A Songwriter    0.0349    0.0252     1.38  0.167    Positive 
## 11 Multiple Lead Vocalists   0.0292    0.0205     1.43  0.154    Positive 
## 12 Vocally Based             0.0219    0.0199     1.10  0.271    Positive 
## 13 Log Acousticness         -0.0198    0.0236    -0.840 0.401    Negative 
## 14 Explicit                  0.0193    0.0245     0.787 0.432    Positive 
## 15 Rock                     -0.0182    0.0404    -0.451 0.652    Negative
\end{verbatim}

\paragraph{Result Interpretation}\label{result-interpretation}

The linear regression model shows weak predictive performance for
explaining the number of weeks a song remains at number one on the
Billboard chart. Cross-validation produced an average \(R^2 = 0.063\)
with \texttt{RMSE\ =\ 0.505} and \texttt{MAE\ =\ 0.415}, while
evaluation on the test set yielded similar results (\(R^2 = 0.052\),
\texttt{RMSE\ =\ 0.502}, \texttt{MAE\ =\ 0.395}). The similarity between
cross-validation and test metrics suggests that the model generalizes
consistently and does not suffer from substantial overfitting. However,
the low \(R^2\) values indicate that the predictors explain only a small
portion of the variation in chart longevity.

The predicted versus actual plot further illustrates this limitation.
Predictions tend to cluster around relatively low values regardless of
the true outcome, indicating that the model struggles to capture songs
that remain at number one for longer periods. Instead the prediction
gravitate toward the average, suggesting the model is unable to identify
strong signals that distinguish highly successful songs from others.

Among the predictors, energy has the strongest standardized effect
(\(\beta = -0.119, p < 0.001\)), indicating that lower-energy songs are
associated with slightly longer duration at number one. Loudness
(\(\beta = 0.096, p < 0001\)) and overall rating
(\(\beta = 0.061, p = 0.003\)) show positive and statistically
significant relationships with chart longevity, suggesting that songs
with stronger perceived production intensity and higher ratings may
remain popular for longer periods. Some structural features such as
vocal introduction and handclasps/snaps also show modest positive
associations, while elements like horns/winds and guitar-based
instrumentation show small negative effects.

However, most predictors are not are not statistically significant,
indicating that these characteristics contribute little predictive
signal once audio features are accounted for. Overall, these findings
suggest that musical attributes alone are insufficient to explain how
long a song remains at number one.

\subsubsection{Discussion}\label{discussion}

The objective of our analysis was to use a linear regression model to
predict the number of weeks a song would remain at the \#1 spot of the
Billboard Hot 100 song rankings (\texttt{weeks\_at\_number\_one}) given
open source data. Unnecessary features and features risking data-leakage
into the predictive model were removed, and the skewed numerical
features were transformed. One Hot Encoding was applied on categorical
features, including genre and musical key; to predict on the data.
Following this preprocessing, the linear regression model was trained
the predictions were compared to the ground truth of weeks at the \#1
spot. We found that in spite of its limited predictive power, that the
model generalizes well onto unseen data due to the small difference
between training and testing error, and that the top 3 statistically
significant features involved in prediction were Energy, Loudness, and
overall rating. From the coefficient values, we can conclude that weeks
a song remains at the number one position is most associated with lower
energy, higher loudness, and higher overall popularity.

Previous literature has also investigated song popularity with various
models including KNN, linear regression, Random forest (and other
tree-based models), and neural networks. Although these models have
varying levels of predictive performance, song popularity is documented
as a challenge to predict due to the nuanced level of the problem.
Factors including individual preferences, globalization of music through
various streaming platforms, and global events contribute to the
challenge of measuring and influencing song popularity. (Terroso-Saenz
et al. 2023) Further, global music trends and top performing artists
have shifted since the introduction of streaming platforms, and song
lengths have decreased to adjust to preferences over time. (Kim 2021;
Terroso-Saenz et al. 2023) Since our analysis spans multiple decades,
world events, and to the adjustment of streaming platforms, these
external factors could be influencing our \(R^2\) value and error
metrics. This means that songs with popular characteristic features
leading to a high number of weeks at the top position from the 1950's or
60's, may not generalize well to features from popular songs in the 21st
century. Therefore, the low preodicitive power of our model was
expected.

A specific example of classifier implementation was conducted by Kim in
2021. This study, similar to the present study, investigated the impact
of various features contributing to song popularity from 2010-2019 using
Spotify data, and analyzed the performance through the RMSE of logistic
regression, KNN, and Random Forest models. The lowest RMSE score was
associated with the logistic regression model, followed by KNN and
Random forest. (Kim 2021)

Overall, this regression model provides good predictions given the data,
historical trends in music forecasting, and questions being
investigated; in spite of its weak predictive patterns. It adds to
previous literature, by implementing different features and conducting a
longitudinal study. The impact of our results can be used to determine
how trends in music have changed overtime. Based on our findings,
improvements/future research quests can be made through training
separate models for the data into the 20th vs the 21st century, or by
decade, to improve performance; while retaining longitudinal nature.

\subsubsection*{References}\label{references}
\addcontentsline{toc}{subsubsection}{References}

\protect\phantomsection\label{refs}
\begin{CSLReferences}{1}{1}
\bibitem[\citeproctext]{ref-billboard}
Billboard Staff. 2011. \emph{About Us: Billboard}.
\url{https://www.billboard.com/music/music-news/about-us-467859/}.

\bibitem[\citeproctext]{ref-tidytuesday}
Data Science Learning Community. 2025. \emph{Tidy Tuesday: A Weekly
Social Data Project}.
\url{https://github.com/rfordatascience/tidytuesday/tree/main/data/2025/2025-08-26}.

\bibitem[\citeproctext]{ref-kim2021}
Kim, J. 2021. {``Music Popularity Prediction Through Data Analysis of
Music's Characteristics.''} \emph{International Journal of Science
Technology and Society} 9 (5): 239.
\url{https://doi.org/10.11648/j.ijsts.20210905.16}.

\bibitem[\citeproctext]{ref-ts2023}
Terroso-Saenz, F., J. Soto, and A Muñoz. 2023. {``Evolution of Global
Music Trends: An Exploratory and Predictive Approach Based on Spotify
Data.''} \emph{Entertainment Computing} 44.
\url{https://doi.org/10.1016/j.entcom.2022.100536}.

\end{CSLReferences}

\end{document}
