<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="May Eindra Tet Toe, Anastasia Tountas, Tran Anh Thu Phung, Harry Nguyen">
<meta name="dcterms.date" content="2026-03-21">

<title>Predicting Billboard #1 Hits</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="billboard_number_one_prediction_files/libs/clipboard/clipboard.min.js"></script>
<script src="billboard_number_one_prediction_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="billboard_number_one_prediction_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="billboard_number_one_prediction_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="billboard_number_one_prediction_files/libs/quarto-html/popper.min.js"></script>
<script src="billboard_number_one_prediction_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="billboard_number_one_prediction_files/libs/quarto-html/anchor.min.js"></script>
<link href="billboard_number_one_prediction_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="billboard_number_one_prediction_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="billboard_number_one_prediction_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="billboard_number_one_prediction_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="billboard_number_one_prediction_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of Contents</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary"><span class="header-section-number">1</span> Summary</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">2</span> Introduction</a></li>
  <li><a href="#methods-and-results" id="toc-methods-and-results" class="nav-link" data-scroll-target="#methods-and-results"><span class="header-section-number">3</span> Methods and Results</a>
  <ul class="collapse">
  <li><a href="#overview-of-our-methodology" id="toc-overview-of-our-methodology" class="nav-link" data-scroll-target="#overview-of-our-methodology"><span class="header-section-number">3.1</span> Overview of our Methodology</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">3.2</span> Exploratory Data Analysis</a></li>
  <li><a href="#feature-transformations-selection" id="toc-feature-transformations-selection" class="nav-link" data-scroll-target="#feature-transformations-selection"><span class="header-section-number">3.3</span> Feature Transformations &amp; Selection</a></li>
  <li><a href="#modeling" id="toc-modeling" class="nav-link" data-scroll-target="#modeling"><span class="header-section-number">3.4</span> Modeling</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">3.5</span> Results</a></li>
  <li><a href="#result-interpretation" id="toc-result-interpretation" class="nav-link" data-scroll-target="#result-interpretation"><span class="header-section-number">3.6</span> Result Interpretation</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">4</span> Discussion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">5</span> References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting Billboard #1 Hits</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>May Eindra Tet Toe, Anastasia Tountas, Tran Anh Thu Phung, Harry Nguyen </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 21, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="summary" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Summary</h1>
<p>The objective of this analysis is to use publicly available song information from the Billboard Hot 100 song rankings to investigate the question:</p>
<p><strong>Given various metrics about a song (energy, beats per minute, etc.), how many weeks, if any, will a song remain at the top position in the Billboard Hot 100 rankings? Which features contribute most to our model’s predictions?</strong></p>
</section>
<section id="introduction" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introduction</h1>
<p>The magazine “Billboard” is a leading source of information on trends in music popularity and innovation. Following the launch of the magazine in 1958, weekly rankings of the top 100 songs in the US have been made publicly available <span class="citation" data-cites="billboard">(<a href="#ref-billboard" role="doc-biblioref">Billboard Staff 2011</a>)</span>. The dataset that we have selected is open-source Tidy Tuesday <span class="citation" data-cites="tidytuesday">(<a href="#ref-tidytuesday" role="doc-biblioref">Data Science Learning Community 2025</a>)</span> dataset which documents these billboard rankings from August 4th 1958, until January 11th 2025. It provides features such as lyrics, song-structure, and featured_artists for each song in the ranking. These features can then be used for song popularity predictions or music trend forecasting. In this analysis, we use linear regression to predict the number of weeks a song remains at the #1 spot in the rankings, and assess our model’s performance using RMSE, MAE and <span class="math inline">\(R^2\)</span>. Even though our results show that our regressor has a weak performance, information regarding feature importances in model decision-making remain useful in determining a song’s overall popularity.</p>
</section>
<section id="methods-and-results" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Methods and Results</h1>
<section id="overview-of-our-methodology" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="overview-of-our-methodology"><span class="header-section-number">3.1</span> Overview of our Methodology</h2>
<p>The Billboard Hot 100 dataset provides us with two datasets: <code>billboard.csv</code>, which contains one row per song that reached #1 along with its features, and <code>topics.csv</code>, a reference list of lyrical theme labels (<code>lyrical_topics</code>). Our team decided to combine the two datasets to create more comprehensive data to better equip our model. Here is an overview of our data analysis methodology:</p>
<ol type="1">
<li><strong>Reading &amp; Wrangling:</strong> Read and wrangle the dataset into one tidy combined dataset.</li>
<li><strong>Exploratory Data Analysis:</strong> Explore the data to understand the distribution of features and their relationships with the target variable.</li>
<li><strong>Feature Transformations &amp; Selection:</strong> Apply log transformation to skewed variables, one-hot encode <code>cdr_genre</code>, and collapse <code>simplified_key</code> into three categories. Drop irrelevant columns and use near-zero variance filtering.</li>
<li><strong>Model Building &amp; Evaluation:</strong> Split the data 70/30, fit an ordinary least squares model using a <code>tidymodels</code> workflow. Evaluate the model using repeated 5-fold cross-validation and test set metrics (RMSE, <span class="math inline">\(R^2\)</span>, MAE).</li>
<li><strong>Results and Conclusion:</strong> Summarize findings, discuss implications, and suggest potential future work.</li>
</ol>
</section>
<section id="exploratory-data-analysis" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="exploratory-data-analysis"><span class="header-section-number">3.2</span> Exploratory Data Analysis</h2>
<p>Summary statistics for the target and key predictors:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">read.csv</span>(<span class="st">"../results/tables/summary_stats.csv"</span>), <span class="at">caption =</span> <span class="st">"Table 1: Summary statistics for target and key predictors."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 1: Summary statistics for target and key predictors.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">acousticness</td>
<td style="text-align: right;">31.51</td>
<td style="text-align: right;">27.66</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23.00</td>
<td style="text-align: right;">98</td>
</tr>
<tr class="even">
<td style="text-align: left;">bpm</td>
<td style="text-align: right;">115.50</td>
<td style="text-align: right;">23.69</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">115.00</td>
<td style="text-align: right;">176</td>
</tr>
<tr class="odd">
<td style="text-align: left;">danceability</td>
<td style="text-align: right;">62.45</td>
<td style="text-align: right;">15.21</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">64.00</td>
<td style="text-align: right;">98</td>
</tr>
<tr class="even">
<td style="text-align: left;">energy</td>
<td style="text-align: right;">59.81</td>
<td style="text-align: right;">19.62</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">60.50</td>
<td style="text-align: right;">98</td>
</tr>
<tr class="odd">
<td style="text-align: left;">front_person_age</td>
<td style="text-align: right;">27.97</td>
<td style="text-align: right;">6.51</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">27.50</td>
<td style="text-align: right;">62</td>
</tr>
<tr class="even">
<td style="text-align: left;">happiness</td>
<td style="text-align: right;">62.60</td>
<td style="text-align: right;">24.96</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">68.00</td>
<td style="text-align: right;">99</td>
</tr>
<tr class="odd">
<td style="text-align: left;">length_sec</td>
<td style="text-align: right;">222.88</td>
<td style="text-align: right;">50.12</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">224.00</td>
<td style="text-align: right;">515</td>
</tr>
<tr class="even">
<td style="text-align: left;">loudness_d_b</td>
<td style="text-align: right;">-9.02</td>
<td style="text-align: right;">3.40</td>
<td style="text-align: right;">-23</td>
<td style="text-align: right;">-9.00</td>
<td style="text-align: right;">-1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">overall_rating</td>
<td style="text-align: right;">6.18</td>
<td style="text-align: right;">1.86</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6.33</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">weeks_at_number_one</td>
<td style="text-align: right;">2.91</td>
<td style="text-align: right;">2.49</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">16</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Distribution of weeks at number one:</p>
<p><img src="../results/figures/target_distribution.png" class="img-fluid"> <em>Figure 1: Distribution of weeks at number one.</em></p>
<p>Distributions of the five Spotify audio features:</p>
<p><img src="../results/figures/audio_feature_distribution.png" class="img-fluid"> <em>Figure 2: Distributions of the five Spotify audio features.</em></p>
<p>Average weeks at number one by genre:</p>
<p><img src="../results/figures/average_week.png" class="img-fluid"> <em>Figure 3: Average weeks at number one by genre.</em></p>
</section>
<section id="feature-transformations-selection" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="feature-transformations-selection"><span class="header-section-number">3.3</span> Feature Transformations &amp; Selection</h2>
<ul>
<li>Log transformation applied to right-skewed variables (<code>weeks_at_number_one</code>, <code>acousticness</code>).</li>
<li>One-hot encoding for multi-label genres.</li>
<li>Collapsed musical keys into Major, Minor, and Multiple Keys.</li>
<li>Dropped redundant, high-cardinality, and ambiguous columns.</li>
<li>Removed near-zero variance predictors.</li>
</ul>
</section>
<section id="modeling" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="modeling"><span class="header-section-number">3.4</span> Modeling</h2>
<ul>
<li>Data split into training (70%) and testing (30%) sets.</li>
<li>Linear regression model built using tidymodels workflow.</li>
<li>Model evaluated with repeated 5-fold cross-validation and on the test set.</li>
</ul>
</section>
<section id="results" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="results"><span class="header-section-number">3.5</span> Results</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">read.csv</span>(<span class="st">"../results/tables/cv_metrics.csv"</span>), <span class="at">caption =</span> <span class="st">"Table 2: Cross-validation metrics (RMSE, R^2, MAE)."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 2: Cross-validation metrics (RMSE, R^2, MAE).</caption>
<thead>
<tr class="header">
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">std_err</th>
<th style="text-align: left;">.config</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mae</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.4149415</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.0059948</td>
<td style="text-align: left;">pre0_mod0_post0</td>
</tr>
<tr class="even">
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.5048772</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.0067436</td>
<td style="text-align: left;">pre0_mod0_post0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rsq</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0625536</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.0112796</td>
<td style="text-align: left;">pre0_mod0_post0</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">read.csv</span>(<span class="st">"../results/tables/test_metrics.csv"</span>), <span class="at">caption =</span> <span class="st">"Table 3: Test set metrics (RMSE, R^2, MAE)."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 3: Test set metrics (RMSE, R^2, MAE).</caption>
<thead>
<tr class="header">
<th style="text-align: left;">.metric</th>
<th style="text-align: left;">.estimator</th>
<th style="text-align: right;">.estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.5016631</td>
</tr>
<tr class="even">
<td style="text-align: left;">rsq</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.0518325</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mae</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.3949391</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Actual vs predicted weeks at number one (test set):</p>
<p><img src="../results/figures/actual_vs_predicted.png" class="img-fluid"> <em>Figure 4: Actual vs predicted weeks at number one on the test set (original scale).</em></p>
<p>Top 15 predictors by standardized coefficient magnitude:</p>
<p><img src="../results/figures/top_15_coefficients.png" class="img-fluid"> <em>Figure 5: Top 15 predictors by standardized coefficient magnitude.</em></p>
</section>
<section id="result-interpretation" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="result-interpretation"><span class="header-section-number">3.6</span> Result Interpretation</h2>
<p>The linear regression model shows weak predictive performance for explaining the number of weeks a song remains at number one on the Billboard chart. Cross-validation produced an average <span class="math inline">\(R^2 = 0.063\)</span> with RMSE = 0.505 and MAE = 0.415, while evaluation on the test set yielded similar results (<span class="math inline">\(R^2 = 0.052\)</span>, RMSE = 0.502, MAE = 0.395). The similarity between cross-validation and test metrics suggests that the model generalizes consistently and does not suffer from substantial overfitting. However, the low <span class="math inline">\(R^2\)</span> values indicate that the predictors explain only a small portion of the variation in chart longevity.</p>
<p>The predicted versus actual plot further illustrates this limitation. Predictions tend to cluster around relatively low values regardless of the true outcome, indicating that the model struggles to capture songs that remain at number one for longer periods. Instead, the predictions gravitate toward the average, suggesting the model is unable to identify strong signals that distinguish highly successful songs from others.</p>
<p>Among the predictors, energy has the strongest standardized effect (<span class="math inline">\(\beta = -0.119, p &lt; 0.001\)</span>), indicating that lower-energy songs are associated with slightly longer duration at number one. Loudness (<span class="math inline">\(\beta = 0.096, p &lt; 0.001\)</span>) and overall rating (<span class="math inline">\(\beta = 0.061, p = 0.003\)</span>) show positive and statistically significant relationships with chart longevity, suggesting that songs with stronger perceived production intensity and higher ratings may remain popular for longer periods. Some structural features such as vocal introduction and handclasps/snaps also show modest positive associations, while elements like horns/winds and guitar-based instrumentation show small negative effects.</p>
<p>However, most predictors are not statistically significant, indicating that these characteristics contribute little predictive signal once audio features are accounted for. Overall, these findings suggest that musical attributes alone are insufficient to explain how long a song remains at number one.</p>
</section>
</section>
<section id="discussion" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Discussion</h1>
<p>The objective of our analysis was to use a linear regression model to predict the number of weeks a song would remain at the #1 spot of the Billboard Hot 100 song rankings (<code>weeks_at_number_one</code>) given open source data. Unnecessary features and features risking data-leakage into the predictive model were removed, and the skewed numerical features were transformed. One-hot encoding was applied on categorical features, including genre and musical key. Following this preprocessing, the linear regression model was trained and the predictions were compared to the ground truth of weeks at the #1 spot. We found that in spite of its limited predictive power, the model generalizes well onto unseen data due to the small difference between training and testing error, and that the top 3 statistically significant features involved in prediction were Energy, Loudness, and overall rating. From the coefficient values, we can conclude that weeks a song remains at the number one position is most associated with lower energy, higher loudness, and higher overall popularity.</p>
<p>Previous literature has also investigated song popularity with various models including KNN, linear regression, Random forest (and other tree-based models), and neural networks. Although these models have varying levels of predictive performance, song popularity is documented as a challenge to predict due to the nuanced level of the problem. Factors including individual preferences, globalization of music through various streaming platforms, and global events contribute to the challenge of measuring and influencing song popularity <span class="citation" data-cites="ts2023">(<a href="#ref-ts2023" role="doc-biblioref">Terroso-Saenz, Soto, and Muñoz 2023</a>)</span>. Further, global music trends and top performing artists have shifted since the introduction of streaming platforms, and song lengths have decreased to adjust to preferences over time <span class="citation" data-cites="kim2021 ts2023">(<a href="#ref-kim2021" role="doc-biblioref">Kim 2021</a>; <a href="#ref-ts2023" role="doc-biblioref">Terroso-Saenz, Soto, and Muñoz 2023</a>)</span>. Since our analysis spans multiple decades, world events, and the adjustment of streaming platforms, these external factors could be influencing our <span class="math inline">\(R^2\)</span> value and error metrics. This means that songs with popular characteristic features leading to a high number of weeks at the top position from the 1950’s or 60’s, may not generalize well to features from popular songs in the 21st century. Therefore, the low predictive power of our model was expected.</p>
<p>A specific example of classifier implementation was conducted by Kim in 2021. This study, similar to the present study, investigated the impact of various features contributing to song popularity from 2010-2019 using Spotify data, and analyzed the performance through the RMSE of logistic regression, KNN, and Random Forest models. The lowest RMSE score was associated with the logistic regression model, followed by KNN and Random forest <span class="citation" data-cites="kim2021">(<a href="#ref-kim2021" role="doc-biblioref">Kim 2021</a>)</span>.</p>
<p>Overall, this regression model provides good predictions given the data, historical trends in music forecasting, and questions being investigated; in spite of its weak predictive patterns. It adds to previous literature, by implementing different features and conducting a longitudinal study. The impact of our results can be used to determine how trends in music have changed overtime. Based on our findings, improvements/future research quests can be made through training separate models for the data into the 20th vs the 21st century, or by decade, to improve performance; while retaining longitudinal nature.</p>
</section>
<section id="references" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> References</h1>
<p>All references will be automatically included here from references.bib.</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-billboard" class="csl-entry" role="listitem">
Billboard Staff. 2011. <span>“About Us: Billboard.”</span> <a href="https://www.billboard.com/music/music-news/about-us-467859/">https://www.billboard.com/music/music-news/about-us-467859/</a>.
</div>
<div id="ref-tidytuesday" class="csl-entry" role="listitem">
Data Science Learning Community. 2025. <span>“Tidy Tuesday: A Weekly Social Data Project.”</span> <a href="https://github.com/rfordatascience/tidytuesday/tree/main/data/2025/2025-08-26">https://github.com/rfordatascience/tidytuesday/tree/main/data/2025/2025-08-26</a>.
</div>
<div id="ref-kim2021" class="csl-entry" role="listitem">
Kim, J. 2021. <span>“Music Popularity Prediction Through Data Analysis of Music’s Characteristics.”</span> <em>International Journal of Science Technology and Society</em> 9 (5): 239. <a href="https://doi.org/10.11648/j.ijsts.20210905.16">https://doi.org/10.11648/j.ijsts.20210905.16</a>.
</div>
<div id="ref-ts2023" class="csl-entry" role="listitem">
Terroso-Saenz, F., J. Soto, and A Muñoz. 2023. <span>“Evolution of Global Music Trends: An Exploratory and Predictive Approach Based on Spotify Data.”</span> <em>Entertainment Computing</em> 44. <a href="https://doi.org/10.1016/j.entcom.2022.100536">https://doi.org/10.1016/j.entcom.2022.100536</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>